// Seed de produtos aplicada a cada nova empresa.
// dose e protocolo deixados vazios de proposito: a IA segue a regra
// "NUNCA invente dosagem — responda apenas o que esta cadastrado" e diz
// "deixa eu confirmar com a equipe" quando o campo esta vazio.
// A empresa preenche depois conforme protocolo proprio.

const PRODUTOS_PADRAO = [
  {
    nome: 'AOD-9604 10MG - FRASCO + DILUENTE',
    indicacao: 'Dificuldade em perder gordura localizada — queima de gordura direcionada',
    preco: '1100',
    preco_de: '1500',
    dose: null,
    protocolo: null,
    stack: 'Combina com Tirzepatide ou Retatrutide para resultado acelerado',
    upsell: 'NAD (energia) ou MOTS-C (metabolismo)',
    script_venda: 'Perfeito, pelo que voce me falou, o AOD-9604 encaixa muito bem. Ele e focado em ajudar o corpo a queimar gordura, principalmente pra quem tem dificuldade em perder — acelera o processo sem precisar fazer nada extremo. Se fizer sentido, posso montar o protocolo ideal pra voce comecar.',
    ordem: 1,
  },
  {
    nome: 'RETATRUTIDE 40MG - FRASCO + DILUENTE',
    indicacao: 'Emagrecimento expressivo — quem ja tentou outros recursos e quer resultado mais forte',
    preco: '2000',
    preco_de: '2300',
    dose: null,
    protocolo: null,
    stack: 'Pode ser combinada com BPC-157 para recuperacao',
    upsell: 'Tirzepatide como upgrade premium',
    script_venda: 'Pra esse nivel de resultado que voce quer, o mais indicado seria a Retatrutide. Ela atua direto no controle do apetite e acelera bastante o emagrecimento — e pra quem quer resultado mais forte e consistente. Quer que eu te sugira como comecar da melhor forma?',
    ordem: 2,
  },
  {
    nome: 'TIZERPATIDE 60MG - 1 FRASCOS + DILUENTE',
    indicacao: 'Emagrecimento premium — reduz fome de forma natural e gradual, alto indice de adesao',
    preco: '1500',
    preco_de: '2000',
    dose: null,
    protocolo: null,
    stack: 'Combina com NAD para energia durante o protocolo',
    upsell: 'Tirzepatide 0,5ml/15mg (4 frascos) para protocolo extendido',
    script_venda: 'Hoje, o que mais tem dado resultado nesse objetivo e o Tirzepatide. Ele ajuda a reduzir a fome naturalmente, entao o processo de emagrecimento fica muito mais facil. E um dos protocolos mais usados hoje. Se quiser, te explico certinho como funcionaria pra voce.',
    ordem: 3,
  },
  {
    nome: 'TIZERPATIDE 0,5ML/15MG - 4 FRASCOS',
    indicacao: 'Protocolo extendido de emagrecimento — 4 frascos para 8 semanas ou mais',
    preco: '1700',
    preco_de: '2000',
    dose: null,
    protocolo: null,
    stack: 'Combina com NAD ou MOTS-C',
    upsell: 'Adicionar BPC-157 para recuperacao corporal',
    script_venda: 'Pra quem quer fazer um protocolo mais solido de emagrecimento, esse kit de 4 frascos de Tizerpatide e ideal. Da pra fechar 8 semanas ou mais com tranquilidade, que e o tempo certo pra ver um resultado consistente.',
    ordem: 4,
  },
  {
    nome: 'BPC-157 10MG - FRASCO + DILUENTE',
    indicacao: 'Dores cronicas, lesoes, recuperacao pos-treino intenso',
    preco: '600',
    preco_de: '800',
    dose: null,
    protocolo: null,
    stack: 'Combina muito bem com Ipamorelin para recuperacao + GH',
    upsell: 'Tesamorelin se houver objetivo estetico junto',
    script_venda: 'Pelo que voce comentou, o BPC-157 e o mais indicado. Ele ajuda muito na regeneracao e recuperacao do corpo, principalmente em casos de dor ou lesao. A ideia e acelerar o processo de recuperacao mesmo. Se fizer sentido, posso te orientar como usar.',
    ordem: 5,
  },
  {
    nome: 'PAMORELIN 10MG - FRASCO + DILUENTE',
    indicacao: 'Performance, qualidade de sono e recuperacao para quem treina',
    preco: '1300',
    preco_de: '1500',
    dose: null,
    protocolo: null,
    stack: 'Stack classico com BPC-157 para recuperacao completa',
    upsell: 'Tesamorelin para composicao corporal',
    script_venda: 'Pra performance e recuperacao, o Pamorelin funciona muito bem. Melhora a recuperacao muscular e a qualidade do sono, o que impacta direto no resultado. E bem usado por quem treina. Quer que eu te mostre como encaixar no seu caso?',
    ordem: 6,
  },
  {
    nome: 'TESAMORELIN 10MG - FRASCO + DILUENTE',
    indicacao: 'Performance + reducao de gordura abdominal / composicao corporal',
    preco: '900',
    preco_de: '1100',
    dose: null,
    protocolo: null,
    stack: 'Combina com Pamorelin (Ipamorelin) e BPC-157',
    upsell: 'AOD-9604 se foco for queima de gordura localizada',
    script_venda: 'Se a ideia e melhorar performance e ainda reduzir gordura abdominal, o Tesamorelin e uma otima opcao. Atua direto na composicao corporal — melhora estetica junto com resultado fisico.',
    ordem: 7,
  },
  {
    nome: 'GHK-CU 50MG - FRASCO + DILUENTE',
    indicacao: 'Rejuvenescimento, pele, cabelo e regeneracao geral',
    preco: '600',
    preco_de: '800',
    dose: null,
    protocolo: null,
    stack: 'Pode ser usado junto com o Serum GHK-CU para acao topica e injetavel',
    upsell: 'Serum GHK-CU 200ml para complementar uso topico',
    script_venda: 'Pra estetica e rejuvenescimento, o GHK-CU e o mais indicado. Atua na pele, cabelo e regeneracao. Muito usado por quem quer melhorar a aparencia de forma geral.',
    ordem: 8,
  },
  {
    nome: 'SERUM GHK-CU 200ml | Pele e Cabelo',
    indicacao: 'Acao topica direta para pele e cabelo — rejuvenescimento e brilho',
    preco: '750',
    preco_de: null,
    dose: null,
    protocolo: null,
    stack: 'Complementa o GHK-CU injetavel — uso topico diario',
    upsell: 'GHK-CU 50mg injetavel para resultado interno',
    script_venda: 'Esse Serum de GHK-CU e a versao topica, pra aplicar direto na pele e couro cabeludo. Funciona como complemento do injetavel ou pra quem prefere comecar so com uso topico mesmo.',
    ordem: 9,
  },
  {
    nome: 'KLOW 80MG - FRASCO + DILUENTE',
    indicacao: 'Blend estetico — pele, aparencia e bem-estar visual',
    preco: '1500',
    preco_de: '2000',
    dose: null,
    protocolo: null,
    stack: 'Combina com GHK-CU para resultado estetico potencializado',
    upsell: 'Glow 80mg como alternativa mais leve',
    script_venda: 'O Klow e um blend voltado pra estetica geral. Ajuda na aparencia, pele e sensacao de bem-estar. E pra quem quer se sentir melhor visualmente tambem.',
    ordem: 10,
  },
  {
    nome: 'GLOW 80MG - FRASCO + DILUENTE',
    indicacao: 'Blend estetico — bem-estar e melhora gradual da aparencia',
    preco: '1200',
    preco_de: '1500',
    dose: null,
    protocolo: null,
    stack: 'Combina com Klow ou GHK-CU para estetica completa',
    upsell: 'Klow 80mg para acao mais intensiva',
    script_venda: 'O Glow e o blend estetico mais acessivel — bom pra quem ta comecando ou quer manter o resultado. Atua em pele, aparencia e disposicao geral.',
    ordem: 11,
  },
  {
    nome: 'NAD 100MG - FRASCO + DILUENTE',
    indicacao: 'Cansaco constante, baixa energia, recuperacao celular',
    preco: '1000',
    preco_de: null,
    dose: null,
    protocolo: null,
    stack: 'Combina com MOTS-C para metabolismo e energia',
    upsell: 'MOTS-C para reforco metabolico',
    script_venda: 'Se o seu ponto e energia e disposicao, o NAD e o ideal. Melhora a energia celular e resolve aquele cansaco constante do dia a dia.',
    ordem: 12,
  },
  {
    nome: 'MOTS-C 10MG - FRASCO + DILUENTE',
    indicacao: 'Metabolismo lento, performance interna, emagrecimento leve',
    preco: '750',
    preco_de: '900',
    dose: null,
    protocolo: null,
    stack: 'Combina com NAD para energia + AOD-9604 para emagrecimento',
    upsell: 'NAD se o objetivo principal for energia',
    script_venda: 'O MOTS-C e interessante pra metabolismo e energia — ajuda o corpo a funcionar melhor e pode apoiar no emagrecimento leve. Mais voltado pra performance interna.',
    ordem: 13,
  },
  {
    nome: 'SELANK 10MG - FRASCO + DILUENTE',
    indicacao: 'Ansiedade, falta de foco, rotina corrida',
    preco: '700',
    preco_de: '900',
    dose: null,
    protocolo: null,
    stack: 'Combina com NAD para energia + foco',
    upsell: 'Pamorelin para qualidade de sono',
    script_venda: 'Se o problema for ansiedade ou falta de foco, o Selank e o mais indicado. Ajuda a acalmar e melhorar a concentracao — muito usado pra rotina corrida.',
    ordem: 14,
  },
  {
    nome: 'SLU-PP-332 250mcg CAPSULA',
    indicacao: 'Mimetico de exercicio — apoio metabolico e performance leve via via oral',
    preco: '750',
    preco_de: null,
    dose: null,
    protocolo: null,
    stack: 'Combina com MOTS-C para metabolismo + AOD-9604 para emagrecimento',
    upsell: 'MOTS-C para potencializar acao metabolica',
    script_venda: 'O SLU-PP-332 e em capsula, oral mesmo — pra quem prefere nao injetar. Atua no metabolismo e da um apoio na queima de gordura e disposicao. E uma opcao mais pratica pra quem ta comecando.',
    ordem: 15,
  },
];

module.exports = { PRODUTOS_PADRAO };
